import { Movie } from '../types';

const mockMovies: Movie[] = [
  {
    id: 'tt0111161',
    title: 'The Shawshank Redemption',
    year: '1994',
    posterUrl: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    plot: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    director: 'Frank Darabont',
    actors: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'],
    genre: ['Drama'],
  },
  {
    id: 'tt0068646',
    title: 'The Godfather',
    year: '1972',
    posterUrl: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    plot: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    director: 'Francis Ford Coppola',
    actors: ['Marlon Brando', 'Al Pacino', 'James Caan'],
    genre: ['Crime', 'Drama'],
  },
  {
    id: 'tt0468569',
    title: 'The Dark Knight',
    year: '2008',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    plot: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    director: 'Christopher Nolan',
    actors: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    genre: ['Action', 'Crime', 'Drama'],
  },
  {
    id: 'tt0110912',
    title: 'Pulp Fiction',
    year: '1994',
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    plot: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    director: 'Quentin Tarantino',
    actors: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
    genre: ['Crime', 'Drama'],
  },
  {
    id: 'tt1375666',
    title: 'Inception',
    year: '2010',
    posterUrl: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    plot: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    director: 'Christopher Nolan',
    actors: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    genre: ['Action', 'Adventure', 'Sci-Fi'],
  },
  {
    id: 'tt0816692',
    title: 'Interstellar',
    year: '2014',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    plot: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    director: 'Christopher Nolan',
    actors: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    genre: ['Adventure', 'Drama', 'Sci-Fi'],
  },
  {
    id: 'tt0241527',
    title: "Harry Potter and the Sorcerer's Stone",
    year: '2001',
    posterUrl: 'https://image.tmdb.org/t/p/w500/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg',
    plot: 'An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.',
    director: 'Chris Columbus',
    actors: ['Daniel Radcliffe', 'Rupert Grint', 'Emma Watson'],
    genre: ['Adventure', 'Fantasy', 'Family'],
  },
  {
    id: 'tt0120737',
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    year: '2001',
    posterUrl: 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
    plot: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
    director: 'Peter Jackson',
    actors: ['Elijah Wood', 'Ian McKellen', 'Orlando Bloom'],
    genre: ['Adventure', 'Fantasy', 'Action'],
  },
  {
    id: 'tt0137523',
    title: 'Fight Club',
    year: '1999',
    posterUrl: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    plot: 'An insomniac office worker looking for a way to change his life crosses paths with a devil-may-care soap maker and they form an underground fight club that evolves into something much, much more.',
    director: 'David Fincher',
    actors: ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'],
    genre: ['Drama'],
  },
  {
    id: 'tt0133093',
    title: 'The Matrix',
    year: '1999',
    posterUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    plot: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    director: 'Lana Wachowski, Lilly Wachowski',
    actors: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    genre: ['Action', 'Sci-Fi'],
  },
  {
    id: 'tt0172495',
    title: 'Gladiator',
    year: '2000',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
    plot: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
    director: 'Ridley Scott',
    actors: ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen'],
    genre: ['Action', 'Adventure', 'Drama'],
  },
  {
    id: 'tt0120338',
    title: 'Titanic',
    year: '1997',
    posterUrl: 'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
    plot: 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
    director: 'James Cameron',
    actors: ['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane'],
    genre: ['Drama', 'Romance'],
  },
  {
    id: 'tt6751668',
    title: 'Parasite',
    year: '2019',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    plot: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    director: 'Bong Joon Ho',
    actors: ['Kang-ho Song', 'Sun-kyun Lee', 'Yeo-jeong Cho'],
    genre: ['Thriller', 'Comedy', 'Drama'],
  },
  {
    id: 'tt7286456',
    title: 'Joker',
    year: '2019',
    posterUrl: 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
    plot: 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embark on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.',
    director: 'Todd Phillips',
    actors: ['Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz'],
    genre: ['Crime', 'Drama', 'Thriller'],
  },
  {
    id: 'tt4154796',
    title: 'Avengers: Endgame',
    year: '2019',
    posterUrl: 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    plot: 'Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe.',
    director: 'Anthony Russo, Joe Russo',
    actors: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo'],
    genre: ['Action', 'Adventure', 'Sci-Fi'],
  },
  {
    id: 'tt0109830',
    title: 'Forrest Gump',
    year: '1994',
    posterUrl: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    plot: 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.',
    director: 'Robert Zemeckis',
    actors: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
    genre: ['Comedy', 'Drama', 'Romance'],
  },
  {
    id: 'tt0120689',
    title: 'The Green Mile',
    year: '1999',
    posterUrl: 'https://image.tmdb.org/t/p/w500/velWPhVMQeQKcxggNEU8YmIo52R.jpg',
    plot: 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.',
    director: 'Frank Darabont',
    actors: ['Tom Hanks', 'Michael Clarke Duncan', 'David Morse'],
    genre: ['Crime', 'Drama', 'Fantasy'],
  },
  {
    id: 'tt0108052',
    title: 'Schindler\'s List',
    year: '1993',
    posterUrl: 'https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
    plot: 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
    director: 'Steven Spielberg',
    actors: ['Liam Neeson', 'Ben Kingsley', 'Ralph Fiennes'],
    genre: ['Biography', 'Drama', 'History'],
  },
  {
    id: 'tt0167260',
    title: 'The Lord of the Rings: The Return of the King',
    year: '2003',
    posterUrl: 'https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
    plot: 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
    director: 'Peter Jackson',
    actors: ['Elijah Wood', 'Viggo Mortensen', 'Ian McKellen'],
    genre: ['Action', 'Adventure', 'Fantasy'],
  },
  {
    id: 'tt0167261',
    title: 'The Lord of the Rings: The Two Towers',
    year: '2002',
    posterUrl: 'https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg',
    plot: 'While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron\'s new ally, Saruman, and his hordes of Isengard.',
    director: 'Peter Jackson',
    actors: ['Elijah Wood', 'Ian McKellen', 'Viggo Mortensen'],
    genre: ['Action', 'Adventure', 'Fantasy'],
  },
  {
    id: 'tt0088763',
    title: 'Back to the Future',
    year: '1985',
    posterUrl: 'https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg',
    plot: 'Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the eccentric scientist Doc Brown.',
    director: 'Robert Zemeckis',
    actors: ['Michael J. Fox', 'Christopher Lloyd', 'Lea Thompson'],
    genre: ['Adventure', 'Comedy', 'Sci-Fi'],
  },
  {
    id: 'tt0078748',
    title: 'Alien',
    year: '1979',
    posterUrl: 'https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg',
    plot: 'After a space merchant vessel perceives an unknown transmission as a distress call, it is attacked by a mysterious life form and they soon realize that its life cycle has merely begun.',
    director: 'Ridley Scott',
    actors: ['Sigourney Weaver', 'Tom Skerritt', 'John Hurt'],
    genre: ['Horror', 'Sci-Fi'],
  },
  {
    id: 'tt0083658',
    title: 'Blade Runner',
    year: '1982',
    posterUrl: 'https://image.tmdb.org/t/p/w500/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg',
    plot: 'A blade runner must pursue and terminate four replicants who stole a ship in space, and have returned to Earth to find their creator.',
    director: 'Ridley Scott',
    actors: ['Harrison Ford', 'Rutger Hauer', 'Sean Young'],
    genre: ['Action', 'Drama', 'Sci-Fi'],
  },
  {
    id: 'tt0482571',
    title: 'The Prestige',
    year: '2006',
    posterUrl: 'https://image.tmdb.org/t/p/w500/tRNlZbgNCNOpLpbPEz5L8G8A0JN.jpg',
    plot: 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.',
    director: 'Christopher Nolan',
    actors: ['Hugh Jackman', 'Christian Bale', 'Michael Caine'],
    genre: ['Drama', 'Mystery', 'Sci-Fi'],
  },
  {
    id: 'tt1853728',
    title: 'Django Unchained',
    year: '2012',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg',
    plot: 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.',
    director: 'Quentin Tarantino',
    actors: ['Jamie Foxx', 'Christoph Waltz', 'Leonardo DiCaprio'],
    genre: ['Drama', 'Western'],
  },
  {
    id: 'tt1392190',
    title: 'Mad Max: Fury Road',
    year: '2015',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg',
    plot: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the help of a group of female prisoners, a psychotic worshiper, and a drifter named Max.',
    director: 'George Miller',
    actors: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'],
    genre: ['Action', 'Adventure', 'Sci-Fi'],
  },
  {
    id: 'tt2380307',
    title: 'Coco',
    year: '2017',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg',
    plot: "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
    director: 'Lee Unkrich, Adrian Molina',
    actors: ['Anthony Gonzalez', 'Gael García Bernal', 'Benjamin Bratt'],
    genre: ['Animation', 'Adventure', 'Family'],
  },
];

const fetchMovies = (searchTerm: string = ''): Promise<Movie[]> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      if (!searchTerm) {
        resolve(mockMovies);
      } else {
        const lowercasedTerm = searchTerm.toLowerCase();
        // FIX: Corrected a typo in the variable name from 'lowcasedTerm' to 'lowercasedTerm'.
        const filteredMovies = mockMovies.filter(movie =>
          movie.title.toLowerCase().includes(lowercasedTerm)
        );
        resolve(filteredMovies);
      }
    }, 500); // Simulate network delay
  });
};

export const movieService = {
  fetchMovies,
};